name: kamu_sinavi_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2


environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  rive: ^0.13.20
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  syncfusion_flutter_charts: ^26.2.11
  wiredash: ^2.2.0
  flutter_localization: ^0.2.2
  device_info_plus: ^10.1.2
  concentric_transition: ^1.0.3
  showcaseview: ^3.0.0
  connectivity_plus: ^6.1.4
  #flutter_secure_storage: ^9.2.2
 
  lottie: ^3.3.1
  
  flutter_spinkit: ^5.2.1
  animate_do: ^3.3.4
  flutter_svg: ^2.0.17
  http: ^1.3.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.5
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.1
  emoji_picker_flutter: ^4.3.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.0.0 

  flutter_lints: ^4.0.0
  image: ^4.3.0






flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/

    

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf   
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf   
    
    - family: LeHavreRounded
      fonts:
        - asset: assets/fonts/LeHavreRounded-Bold.ttf


   