// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA22pHTRw7EOdsjM9QMXP0ILAd2Y-zSC6A',
    appId: '1:241474592559:web:6c481d7f2c1f612a518bda',
    messagingSenderId: '241474592559',
    projectId: 'kamucep-f819e',
    authDomain: 'kamucep-f819e.firebaseapp.com',
    storageBucket: 'kamucep-f819e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjeVxd11ggozzWgzRqJxjKMvQ6wdugTR4',
    appId: '1:241474592559:android:83e6f9c383cb0832518bda',
    messagingSenderId: '241474592559',
    projectId: 'kamucep-f819e',
    storageBucket: 'kamucep-f819e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-qiyC-0thaLg2Bi9GrpuyZtFfSg2GtJw',
    appId: '1:241474592559:ios:85ccbe7b1416ed45518bda',
    messagingSenderId: '241474592559',
    projectId: 'kamucep-f819e',
    storageBucket: 'kamucep-f819e.firebasestorage.app',
    iosBundleId: 'com.bekirmese.KamuCEP',
  );
}
